import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import express from 'express';
import {createAuth,hashPassword,verifyPassword} from './auth.mjs';
const origin='https://studio.example.test';
async function fixture(options={}){const dataDir=options.dataDir||fs.mkdtempSync(path.join(os.tmpdir(),'lab-auth-'));const auth=createAuth({dataDir,origin,...options});const app=express();app.use(express.json({limit:'16kb'}));app.use('/api/auth',auth.router);app.get('/private',auth.requireUser,(req,res)=>res.json(req.user));const server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s))});const base=`http://127.0.0.1:${server.address().port}`;return {dataDir,auth,request:async(endpoint,body,cookie,requestOrigin=origin)=>{const headers={};if(body!==undefined){headers['Content-Type']='application/json';if(requestOrigin!==null)headers.Origin=requestOrigin;}if(cookie)headers.Cookie=cookie;const response=await fetch(base+endpoint,{method:body===undefined?'GET':'POST',headers,body:body===undefined?undefined:JSON.stringify(body)});return {status:response.status,cookie:response.headers.get('set-cookie')?.split(';')[0],setCookie:response.headers.get('set-cookie'),body:await response.json()};},close:async()=>{await new Promise(resolve=>server.close(resolve));auth.close();}};}
const alice={email:'Alice@example.test',password:'correct horse battery staple'};
test('scrypt uses random salts and verifies passwords',async()=>{const a=await hashPassword(alice.password),b=await hashPassword(alice.password);assert.notEqual(a,b);assert.equal(await verifyPassword(alice.password,a),true);assert.equal(await verifyPassword('wrong',a),false);assert.equal(await verifyPassword('wrong','malformed'),false);});
test('sessions isolate accounts, rotate at login, persist across restarts, and invalidate on logout',async()=>{let f=await fixture();const dir=f.dataDir;try{const a=await f.request('/api/auth/signup',alice);assert.equal(a.status,201);assert.match(a.setCookie,/HttpOnly/);assert.match(a.setCookie,/SameSite=Lax/);const b=await f.request('/api/auth/signup',{email:'bob@example.test',password:'another excellent password'});assert.notEqual(a.body.user.id,b.body.user.id);assert.equal((await f.request('/private',undefined,a.cookie)).body.email,'alice@example.test');assert.equal((await f.request('/private',undefined,b.cookie)).body.email,'bob@example.test');assert.equal((await f.request('/private')).status,401);assert.equal((await f.request('/api/auth/login',{...alice,password:'incorrect password'})).status,401);const login=await f.request('/api/auth/login',alice,a.cookie);assert.equal(login.status,200);assert.notEqual(login.cookie,a.cookie);assert.equal((await f.request('/private',undefined,a.cookie)).status,401);await f.close();f=await fixture({dataDir:dir});assert.equal((await f.request('/api/auth/session',undefined,login.cookie)).body.user.id,a.body.user.id);assert.equal((await f.request('/api/auth/logout',{},login.cookie)).status,200);assert.equal((await f.request('/private',undefined,login.cookie)).status,401);assert.equal((await f.request('/private',undefined,b.cookie)).status,200);}finally{await f.close();fs.rmSync(dir,{recursive:true,force:true});}});
test('exact origin and invite gates reject unsafe requests',async()=>{const f=await fixture({inviteCode:'private-invitation'});try{assert.equal((await f.request('/api/auth/signup',alice,undefined,null)).status,403);assert.equal((await f.request('/api/auth/signup',alice,undefined,'https://evil.example')).status,403);assert.equal((await f.request('/api/auth/signup',alice)).status,403);const a=await f.request('/api/auth/signup',{...alice,inviteCode:'private-invitation'});assert.equal(a.status,201);assert.equal((await f.request('/api/auth/logout',{},a.cookie,'https://evil.example')).status,403);assert.equal((await f.request('/private',undefined,a.cookie)).status,200);}finally{await f.close();fs.rmSync(f.dataDir,{recursive:true,force:true});}});
test('expiry and persistent rate limiting apply',async()=>{let clock=Date.now();let f=await fixture({now:()=>clock,loginLimit:2});const dir=f.dataDir;try{const a=await f.request('/api/auth/signup',alice);assert.equal(a.status,201);await f.request('/api/auth/login',{...alice,password:'incorrect password'});await f.close();f=await fixture({dataDir:dir,now:()=>clock,loginLimit:2});assert.equal((await f.request('/api/auth/login',alice)).status,429);clock+=16*60*1000;assert.equal((await f.request('/api/auth/login',alice)).status,200);clock+=8*24*60*60*1000;assert.equal((await f.request('/private',undefined,a.cookie)).status,401);}finally{await f.close();fs.rmSync(dir,{recursive:true,force:true});}});
test('saas startup fails closed without HTTPS and secure cookies',()=>{const dataDir=fs.mkdtempSync(path.join(os.tmpdir(),'lab-auth-config-'));try{assert.throws(()=>createAuth({dataDir,mode:'saas'}),/APP_ORIGIN/);assert.throws(()=>createAuth({dataDir,mode:'saas',origin:'http://example.com',secureCookies:true}),/HTTPS/);assert.throws(()=>createAuth({dataDir,mode:'saas',origin}),/secure/);}finally{fs.rmSync(dataDir,{recursive:true,force:true});}});
