import test from 'node:test';import assert from 'node:assert/strict';import {createBrandPresets} from './brand-presets.mjs';
function setup(fail=false){const db={projects:{p:{ownerId:'a'}},assets:{r:{id:'r',projectId:'p',kind:'reference-image',url:'/media/r.png',name:'reference'},foreign:{id:'foreign',projectId:'q',kind:'reference-image'}}};let persisted;const s=createBrandPresets({db,save(){if(fail)throw Error('disk');persisted=JSON.parse(JSON.stringify(db))},getProject(pid,owner){if(db.projects[pid]?.ownerId!==owner)throw Error('not found');return db.projects[pid]}});return {s,db,get persisted(){return persisted}}}
test('preset persists instructions and owned reference without generation',()=>{const x=setup();const p=x.s.create('p','a',{name:' Brand ',instructions:' Warm lighting ',referenceImageId:'r'});assert.equal(p.name,'Brand');assert.equal(p.instructions,'Warm lighting');assert.equal(x.persisted.projects.p.brandPresets[p.id].referenceImageId,'r');assert.equal(x.s.list('p','a')[0].referenceImage.url,'/media/r.png');assert.equal(x.db.jobs,undefined)});
test('reject foreign owner, foreign reference and invalid input',()=>{const {s}=setup();assert.throws(()=>s.list('p','b'));assert.throws(()=>s.create('p','b',{}));assert.throws(()=>s.create('p','a',{name:'x',instructions:'y',referenceImageId:'foreign'}));for(const input of [{},{name:'x',instructions:''},{name:'x'.repeat(61),instructions:'y'}])assert.throws(()=>s.create('p','a',input))});
test('save failure restores previous state',()=>{const {s,db}=setup(true);assert.throws(()=>s.create('p','a',{name:'x',instructions:'y'}));assert.equal(db.projects.p.brandPresets,undefined)});

test('edit, delete and restore preserve the saved reference',()=>{const {s}=setup();const p=s.create('p','a',{name:'A',instructions:'B',referenceImageId:'r'});assert.equal(s.update('p','a',p.id,{name:'New',instructions:'Style'}).referenceImageId,'r');assert.equal(s.update('p','a',p.id,{deleted:true}).deleted,true);assert.equal(s.update('p','a',p.id,{deleted:false}).deleted,false);assert.equal(s.update('p','a',p.id,{name:'New',instructions:'Style',referenceImageId:''}).referenceImage,undefined);assert.throws(()=>s.update('p','b',p.id,{deleted:true}));});
test('copy owns a separate reference and rejects another owner',()=>{const db={projects:{p:{id:'p',ownerId:'a'},q:{id:'q',ownerId:'a'},foreign:{id:'foreign',ownerId:'b'}},assets:{r:{id:'r',kind:'reference-image',projectId:'p',url:'/media/r.png'}}};const s=createBrandPresets({db,save(){},getProject(id,owner){if(db.projects[id]?.ownerId!==owner)throw Error('not found');return db.projects[id]},copyReference(a,pid){return {...a,id:'copy',projectId:pid,url:'/media/copy.png'}}});const p=s.create('p','a',{name:'A',instructions:'B',referenceImageId:'r'});const c=s.copy('q','a','p',p.id);assert.equal(c.referenceImageId,'copy');assert.equal(db.assets.copy.projectId,'q');assert.notEqual(c.id,p.id);s.update('q','a',c.id,{name:'Changed',instructions:'C'});assert.equal(s.list('p','a')[0].name,'A');assert.throws(()=>s.copy('foreign','a','p',p.id));assert.throws(()=>s.copy('q','b','p',p.id));assert.equal(s.catalog('b').length,0);});
test('failed copy removes copied asset and preserves source',()=>{const {s,db}=setup();const p=s.create('p','a',{name:'A',instructions:'B',referenceImageId:'r'});db.projects.q={ownerId:'a'};let cleaned=false;const failing=createBrandPresets({db,save(){throw Error('disk')},getProject(id){return db.projects[id]},copyReference(a,pid){return {...a,id:'copy',projectId:pid,cleanup(){cleaned=true}}}});assert.throws(()=>failing.copy('q','a','p',p.id));assert.equal(cleaned,true);assert.equal(db.assets.copy,undefined);assert.equal(db.projects.q.brandPresets,undefined);assert.equal(s.list('p','a').length,1);});
