export function qualityChecks(candidate={}){
 const t=candidate.transformationVerification;
 const transformationVerified=t?.outsideCoverage==='preserved'&&Number.isInteger(t.verifiedFrames)&&t.verifiedFrames>0&&Number.isInteger(t.editedFrames)&&t.editedFrames>0&&t.editedFrames<=t.verifiedFrames;
 if(t?.pipeline==='scene-replacement-v1'&&transformationVerified)return [{id:'scene-scope',title:'Entire scene replaced in the selected interval',status:'review',detail:'Camera, environment and objects may all change. This is not an object-preserving edit. Review the start and end cuts.'},{id:'scene-time',title:'Frames outside the interval preserved',status:'verified',detail:`${t.verifiedFrames} decoded output frames checked against the intended composition. Source audio is retained and re-encoded.`}];
 if(t?.pipeline==='foreground-transfer-v1'&&transformationVerified)return [{id:'foreground-scope',title:'Original pixels outside repair coverage preserved',status:'verified',detail:`${t.verifiedFrames} decoded frames checked. Background under the old object uses observed source donors.`},{id:'foreground-view',title:'Generated viewpoint is retained',status:'review',detail:'Placement does not reconstruct a new 3D view. Review silhouette, contact shadows, background restoration, occlusion and cut boundaries.'}];
 if(t?.pipeline==='bounded-transformation-v1'&&t.outsideCoverage==='preserved'&&t.verifiedFrames>0)return [{id:'transformation-preservation',title:'Outside transformation coverage preserved',status:'verified',detail:`${t.verifiedFrames} decoded frames verified. Shape and movement can change inside the approved repair area.`},{id:'transformation-background',title:'Review reconstructed background and motion',status:'review',detail:'Exposed background is inferred from generated footage, not recovered ground truth. Check identity, occlusion, contact shadows and seams. Camera alignment is a geometric check, not a realism guarantee.'}];
 const local=candidate.localVerification;
 if(local&&(local.verifiedFrames>0||local.videoStreamCopied===true))return [{id:'local-edit',title:'Deterministic edit',status:'verified',detail:local.videoStreamCopied?'Original compressed video stream copied without re-encoding.':`${local.verifiedFrames} decoded output frames matched the deterministic render after lossless encoding. ${local.outsideAllowedPixels==='preserved'?'Pixels outside the permitted region stayed unchanged.':'Timing or framing changes follow the reviewed operation.'}`},{id:'local-review',title:'Review the result',status:'review',detail:'Check the selected range, tracking, text, framing and audio. Pixel preservation is not proof that the intended region was selected.'}];
 const precise=candidate.precisionVerification;
 if(precise?.pipeline==='precision-hue-v1'&&precise.verifiedFrames>0&&precise.changedPixels>0&&precise.outsideAllowedPixels==='preserved'&&precise.geometry==='no-spatial-resampling')return [
 {id:'precision',title:'Original motion and geometry retained',status:'verified',detail:`${precise.verifiedFrames} decoded frames verified after lossless encoding. No generated footage or spatial resampling. Only matching-color pixels inside the reviewed mask were allowed to change.`},
 {id:'color-review',title:'Review the selected surface and color',status:'review',detail:'Tracking can select the wrong surface. Check the full range. Similar colors inside the mask can change; neutral and dark details are excluded.'}];
 const proof=candidate.repairVerification;
 const verified=proof?.pipeline==='adaptive-object-repair-v1'&&proof.outsideCoverage==='preserved'&&Number.isInteger(proof.verifiedFrames)&&proof.verifiedFrames>0&&Number.isInteger(proof.editedFrames)&&proof.editedFrames>0&&proof.editedFrames<=proof.verifiedFrames;
 return [{id:'preservation',title:'Unchanged surroundings',status:verified?'verified':'review',detail:verified?`${proof.verifiedFrames} decoded frames checked. Pixels outside the green cleanup coverage are preserved; cleanup may extend beyond your drawn outline.`:'No automatic pixel-preservation proof is available for this candidate. Compare it with the current revision.'},
 ...(proof?.qualityDiagnostics?.flaggedFrames>0?[{id:'tracking-flags',title:'Tracking and generated-object differences',status:'review',detail:`${proof.qualityDiagnostics.flaggedFrames} frames flagged for large cleanup, selection jumps, or replacement position/shape differences. Check near ${(proof.qualityDiagnostics.warnings||[]).slice(0,5).map(w=>Number(w.seconds).toFixed(2)+'s').join(', ')}. These are heuristic warnings, not a measured accuracy score.`}]:[]),
 {id:'motion',title:'Edges and motion',status:'review',detail:'Play the full range. Look for leftover parts, flicker, disappearing details, and changes when objects overlap.'},
 ...(candidate.referenceImage?[{id:'reference',title:'Reference likeness',status:'review',detail:'Compare shape, color, texture, and identifying details with the supplied image. Reference likeness is not automatically verified.'}]:[])];
}
