import test from 'node:test';import assert from 'node:assert/strict';import {editImpact,generationButton} from './edit-impact.mjs';
test('picture scope cannot imply object preservation',()=>{assert.match(editImpact('picture').changes,/entire picture/);assert.match(editImpact('picture').review,/Object edit/)});
test('object promise is limited to verified coverage',()=>{assert.match(editImpact('object').preserves,/outside the final repair coverage/);assert.match(editImpact('object').review,/can change/)});
test('paid action displays estimate and never calls missing pricing free',()=>{assert.equal(generationButton({route:{kind:'higgsfield',estimatedUsd:2.98}}),'Generate preview · est. $2.98');assert.match(generationButton({route:{kind:'higgsfield'}}),/paid/);assert.equal(generationButton({route:{kind:'local'}}),'Create preview')});
import {editScope,reservationLabel} from './edit-impact.mjs';
test('scope distinguishes one frame, full clip and selected range',()=>{assert.equal(editScope({start:2.433333,end:2.466667},5),'This frame only · 1 frame');assert.equal(editScope({start:0,end:5},5),'Whole clip · 150 frames');assert.equal(editScope({start:1,end:3},5),'Selected range · 60 frames')});
test('reservation wording never presents a hold as a verified charge',()=>{assert.match(reservationLabel({route:{kind:'higgsfield',estimatedUsd:1.74}}),/\$3.48.*not a provider charge/);assert.equal(reservationLabel({route:{kind:'local'}}),null)});
test('released provider hold replaces the estimate rather than claiming money is held',()=>{
 assert.equal(reservationLabel({route:{kind:'higgsfield',estimatedUsd:2.55}},{billing:'Provider confirmed no charge; budget reservation released'}),'Provider confirmed no charge; budget reservation released');
 assert.match(reservationLabel({route:{kind:'higgsfield',estimatedUsd:2.55}}),/Budget hold/);
});

import {formatUSD,pricingDetails,confirmedChargeLabel} from './edit-impact.mjs';
test('small positive prices remain visible, only zero is $0.00',()=>{assert.equal(formatUSD(0),'$0.00');assert.equal(formatUSD(.000123),'$0.000123');assert.equal(formatUSD(.001),'$0.001');assert.equal(formatUSD(.0000001),'<$0.000001');assert.equal(formatUSD(4.8),'$4.80');});
test('historical job quote wins over new plan estimate and never implies actual charge',()=>{const label=reservationLabel({route:{kind:'higgsfield',estimatedUsd:.1}},{quote:{estimatedUsd:4.8,reservedUsd:9.6},billing:'Estimate reserved; actual charge not yet reconciled'});assert.match(label,/\$9.60/);assert.match(label,/Final charge not confirmed/);assert.equal(confirmedChargeLabel({confirmedCharge:{actualUsd:0}}),'Final charge confirmed: $0.00.');});
test('pricing detail identifies assumptions and formula versus provider quote',()=>{const rows=pricingDetails({pricingBasis:'provider-formula',pricingDimensions:{width:1280,height:720,inputSeconds:10,outputSeconds:10},rateUsdPer1000Tokens:.01284,billableVideoTokens:432000,quotedAt:'2026-09-22T00:00:00Z'}).join(' ');assert.match(rows,/formula/);assert.match(rows,/10 seconds in \+ 10 seconds out/);assert.match(rows,/assumptions/);assert.match(rows,/\$0.01284/);assert.match(pricingDetails({estimatedUsd:4.8}).join(' '),/not recorded/);assert.match(pricingDetails({pricingBasis:'authenticated-provider-estimate'}).join(' '),/returned by the provider/);});
test('confirmed charge describes old hold as released',()=>{const value=reservationLabel({route:{kind:'higgsfield',estimatedUsd:4.8}},{quote:{estimatedUsd:4.8,reservedUsd:9.6},confirmedCharge:{actualUsd:.094}});assert.match(value,/Original budget hold: \$9.60; released/);assert.match(value,/Final charge confirmed: \$0.094/);assert.doesNotMatch(value,/Final charge not confirmed/);});
