import test from 'node:test';import assert from 'node:assert/strict';
import {LOCAL_TOOLS,directLocalTool,localParameters} from './local-tools.mjs';
import {buildEditPlan} from './conversation.mjs';import {EDIT_ACTIONS,classifyEdit} from './decision-router.mjs';import {applyCandidate,undoProject} from './domain.mjs';
const p={id:'p',activeRevisionId:'r',duration:5,width:1280,height:720,fps:30,revisions:[{id:'r',url:'/original'}]};
test('every advertised local tool has a parser, Jev action and executable plan',async()=>{for(const [id,t] of Object.entries(LOCAL_TOOLS)){assert.ok(EDIT_ACTIONS.includes(id));assert.equal(directLocalTool(t.command),id);const args=localParameters(id,t.command);assert.equal(typeof args,'object');const plan=buildEditPlan(p,{text:t.command,baseRevisionId:'r',start:1,end:3,referenceImageId:t.reference?'asset':undefined},{action:id});assert.equal(plan.route.id,'deterministic',id);assert.equal(plan.tool,id);assert.notEqual(plan.action,'clarify',id);assert.equal(plan.requiresMask,!!t.mask);const decision=await classifyEdit({text:t.command},{env:{}});assert.equal(decision.action,id,id);}});
test('missing numeric input/reference clarifies without paid fallback',()=>{for(const [id,text] of [['speed','make faster'],['title','add a title'],['resize','resize video'],['planar','replace screen']]){const plan=buildEditPlan(p,{text,baseRevisionId:'r',start:1,end:3},{action:id});assert.equal(plan.action,'clarify');assert.equal(plan.route.kind,'local');}});
test('quoted caption numbers are not parsed as timing',()=>{const plan=buildEditPlan(p,{text:'add text "Sale 2 to 4 seconds"',baseRevisionId:'r',start:1,end:3},{action:'title'});assert.equal(plan.start,1);assert.equal(plan.end,3);assert.equal(plan.parameters.text,'Sale 2 to 4 seconds');});
test('crop applies to full video, not a timestamp',()=>{const plan=buildEditPlan(p,{text:'crop 9:16',baseRevisionId:'r',start:1,end:3},{action:'crop'});assert.equal(plan.start,0);assert.equal(plan.end,5);});
test('applying and undoing changed duration/framing restores original metadata',()=>{const next=applyCandidate(p,{id:'c',baseRevisionId:'r',mediaMetadata:{duration:2,width:720,height:1280,fps:30}});assert.equal(next.duration,2);assert.equal(next.width,720);const restored=undoProject(next);assert.equal(restored.duration,5);assert.equal(restored.width,1280);assert.equal(restored.activeRevisionId,'r');});
