import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {createOriginalService,validateOriginal} from './original-generation.mjs';
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'original-test-'));t.after(()=>fs.rmSync(dir,{force:true,recursive:true}));const db={projects:{},spend:{spent:0,reserved:0}};let submits=0,imports=0;const adapter={estimateGeneration:async()=>({estimatedUsd:1,quotedAt:new Date().toISOString()}),submitGeneration:async()=>{submits++;return {requestId:'r',status:'completed',outputUrl:'https://example.com/video.mp4'}},pollGeneration:async p=>({...p,status:'completed'}),uploadAsset:async()=> 'https://example.com/ref.png'};const deps={db,save(){},adapter,mediaPath:id=>path.join(dir,id+'.mp4'),mediaUrl:p=>'/media/'+path.basename(p),runMedia:async q=>fs.writeFileSync(q.output,'safe'),download:async(u,p)=>fs.writeFileSync(p,'video'),importProject:async(f,owner,extra)=>{imports++;const p={id:'project',ownerId:owner,...extra};db.projects.project=p;return p},budgetLimit:()=>10,schedule(){},pause:async()=>{}};return {db,adapter,service:createOriginalService(deps),submits:()=>submits,imports:()=>imports,dir};}
const input={prompt:'A sneaker on a plinth',duration:5,aspectRatio:'16:9'};
test('validate bounded original inputs',()=>{assert.equal(validateOriginal(input).duration,5);for(const patch of [{duration:2},{aspectRatio:'2:1'},{prompt:''}])assert.throws(()=>validateOriginal({...input,...patch}));});
test('original review is free, submit is idempotent, completed clip becomes owned project',async t=>{const f=setup(t),d=f.service.create('a',input);assert.throws(()=>f.service.own(d.id,'b'),/not found/);await f.service.review(d.id,'a');assert.equal(f.submits(),0);await Promise.all([f.service.generate(d.id,'a'),f.service.generate(d.id,'a')]);assert.equal(f.db.spend.reserved,2);await f.service.run(f.service.own(d.id,'a'));assert.equal(f.submits(),1);assert.equal(f.imports(),1);assert.equal(f.service.list('a')[0].projectId,'project');assert.equal(f.db.projects.project.ownerId,'a');assert.equal(f.service.list('b').length,0);});
test('download failure resumes accepted output without another charge',async t=>{const f=setup(t);const d=f.service.create('a',input);await f.service.review(d.id,'a');await f.service.generate(d.id,'a');f.adapter.submitGeneration=async()=>({requestId:'r',status:'in_progress',outputUrl:'https://example.com/video.mp4'});f.adapter.pollGeneration=async()=>{throw new Error('Status temporarily unavailable')};await f.service.run(f.service.own(d.id,'a'));assert.equal(f.service.list('a')[0].canResume,true);f.adapter.pollGeneration=async p=>({...p,status:'completed'});f.service.resume(d.id,'a');await f.service.run(f.service.own(d.id,'a'));assert.equal(f.service.list('a')[0].status,'completed');assert.equal(f.db.spend.reserved,2);});
test('unknown acceptance never exposes a retry that can resubmit',async t=>{const f=setup(t),d=f.service.create('a',input);await f.service.review(d.id,'a');await f.service.generate(d.id,'a');f.adapter.submitGeneration=async()=>({status:'unknown'});await f.service.run(f.service.own(d.id,'a'));assert.equal(f.service.list('a')[0].status,'unknown');assert.throws(()=>f.service.resume(d.id,'a'));});
test('reference ownership and freeze after quoting',async t=>{const f=setup(t),d=f.service.create('a',input);await assert.rejects(()=>f.service.attach(d.id,'b',{}));await f.service.attach(d.id,'a',{path:'test.png',originalname:'shoe.png'});let request;f.adapter.estimateGeneration=async q=>{request=q;return {estimatedUsd:1}};await f.service.review(d.id,'a');assert.equal(request.kind,'reference-to-video');assert.equal(request.imageUrls.length,1);await assert.rejects(()=>f.service.attach(d.id,'a',{path:'x',originalname:'x'}),/before/);assert.equal(f.service.list('a')[0].references[0].providerUrl,undefined);});
test('expired queued quote releases hold without provider submission',async t=>{const f=setup(t),d=f.service.create('a',input);await f.service.review(d.id,'a');await f.service.generate(d.id,'a');const stored=f.service.own(d.id,'a');stored.quote.quotedAt=new Date(Date.now()-360000).toISOString();await f.service.run(stored);assert.equal(f.submits(),0);assert.equal(stored.status,'review');assert.equal(f.db.spend.reserved,0);assert.equal(stored.hold,0);});
test('higher fresh quote requires another review without reserving or submitting',async t=>{const f=setup(t),d=f.service.create('a',input);await f.service.review(d.id,'a');f.adapter.estimateGeneration=async()=>({estimatedUsd:2,quotedAt:new Date().toISOString()});await assert.rejects(()=>f.service.generate(d.id,'a'),/estimate increased/);assert.equal(f.db.spend.reserved,0);assert.equal(f.submits(),0);assert.equal(f.service.list('a')[0].estimate,2);});
