import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import path from 'node:path';import os from 'node:os';import {createHash} from 'node:crypto';import {DatabaseSync} from 'node:sqlite';import {openState} from './state-store.mjs';import {backupWorkspace,restoreWorkspace} from './workspace-transfer.mjs';
function fixture(){const root=fs.mkdtempSync(path.join(os.tmpdir(),'lab-backup-')),source=path.join(root,'source');fs.mkdirSync(path.join(source,'media'),{recursive:true});const media=path.join(source,'media','source.mp4');fs.writeFileSync(media,'test-media');const store=openState(source);Object.assign(store.state,{projects:{p:{id:'p',ownerId:'u',sourcePath:media,revisions:[{id:'r',path:media,url:'/media/source.mp4'}],activeRevisionId:'r'}},assets:{},candidates:{},jobs:{j:{status:'running',generation:{source:media,prompt:media,submission:'accepted',providerState:{requestId:'req',status:'in_progress'}}}},spend:{spent:2,reserved:5},projectDrafts:{p:{version:4,conversation:{text:media}}}});store.save();store.close();const auth=new DatabaseSync(path.join(source,'auth.sqlite'));auth.exec("CREATE TABLE users(id TEXT,email TEXT,password_hash TEXT);CREATE TABLE sessions(token_hash TEXT);CREATE TABLE auth_attempts(bucket TEXT);INSERT INTO users VALUES('u','synthetic@example.test','hash');INSERT INTO sessions VALUES('session');INSERT INTO auth_attempts VALUES('bucket');");auth.close();fs.writeFileSync(path.join(source,'.env'),'NEVER COPY');return {root,source,backup:path.join(root,'backup'),target:path.join(root,'restore'),media};}
const cleanup=f=>{assert.ok(f.root.startsWith(path.resolve(os.tmpdir())+path.sep));fs.rmSync(f.root,{recursive:true,force:true});};
test('backup restores media, ownership, drafts and budget with rebased paths and quarantined jobs',()=>{const f=fixture();try{backupWorkspace(f.source,f.backup);assert.equal(fs.existsSync(path.join(f.backup,'.env')),false);const report=restoreWorkspace(f.backup,f.target);assert.equal(report.quarantinedJobs,1);const store=openState(f.target);assert.equal(store.state.projects.p.sourcePath,path.join(f.target,'media','source.mp4'));assert.equal(store.state.projects.p.ownerId,'u');assert.equal(store.state.projectDrafts.p.version,4);assert.equal(store.state.projectDrafts.p.conversation.text,f.media,'prompt text must not be rebased');assert.equal(store.state.jobs.j.generation.prompt,f.media);assert.equal(store.state.jobs.j.status,'unknown');assert.equal(store.state.jobs.j.generation.providerState.requestId,'req');assert.deepEqual(store.state.spend,{spent:2,reserved:5});store.close();const auth=new DatabaseSync(path.join(f.target,'auth.sqlite'));assert.equal(auth.prepare('SELECT count(*) AS n FROM users').get().n,1);assert.equal(auth.prepare('SELECT count(*) AS n FROM sessions').get().n,0);assert.equal(auth.prepare('PRAGMA integrity_check').get().integrity_check,'ok');auth.close();assert.equal(fs.readFileSync(f.media,'utf8'),'test-media');}finally{cleanup(f)}});
test('active writer, overlapping backup and existing restore target are refused',()=>{const f=fixture();try{const live=openState(f.source);assert.throws(()=>backupWorkspace(f.source,f.backup),/already open/);live.close();assert.throws(()=>backupWorkspace(f.source,path.join(f.source,'nested')),/outside/);backupWorkspace(f.source,f.backup);assert.throws(()=>restoreWorkspace(f.backup,f.source),/exists/);}finally{cleanup(f)}});
test('corrupt media and traversal manifests are rejected before target creation',()=>{const f=fixture();try{backupWorkspace(f.source,f.backup);fs.writeFileSync(path.join(f.backup,'media','source.mp4'),'changed');assert.throws(()=>restoreWorkspace(f.backup,f.target),/integrity/);assert.equal(fs.existsSync(f.target),false);const file=path.join(f.backup,'backup.json'),m=JSON.parse(fs.readFileSync(file));m.files={'../escape':{}};m.files['state.json']={};fs.writeFileSync(file,JSON.stringify(m));assert.throws(()=>restoreWorkspace(f.backup,f.target),/Unsafe/);}finally{cleanup(f)}});

test('missing required media, missing accounts and unrecognized source are refused',()=>{const f=fixture();try{const empty=path.join(f.root,'empty');fs.mkdirSync(empty);assert.throws(()=>backupWorkspace(empty,f.backup));assert.deepEqual(fs.readdirSync(empty),[]);backupWorkspace(f.source,f.backup);const file=path.join(f.backup,'state.json'),state=JSON.parse(fs.readFileSync(file));delete state.projects.p.sourcePath;fs.writeFileSync(file,JSON.stringify(state));const manifestFile=path.join(f.backup,'backup.json'),manifest=JSON.parse(fs.readFileSync(manifestFile));manifest.files['state.json']={bytes:fs.statSync(file).size,sha256:createHash('sha256').update(fs.readFileSync(file)).digest('hex')};fs.writeFileSync(manifestFile,JSON.stringify(manifest));assert.throws(()=>restoreWorkspace(f.backup,f.target),/Missing required/);assert.equal(fs.existsSync(f.target),false);delete manifest.files['auth.sqlite'];fs.writeFileSync(manifestFile,JSON.stringify(manifest));assert.throws(()=>restoreWorkspace(f.backup,f.target),/account database/);}finally{cleanup(f)}});

test('restored media bytes are rechecked after copying',()=>{const f=fixture();const originalCopy=fs.copyFileSync;try{backupWorkspace(f.source,f.backup);fs.copyFileSync=(from,to,...args)=>{originalCopy(from,to,...args);if(String(from).endsWith('source.mp4'))fs.writeFileSync(to,'changed during copy');};assert.throws(()=>restoreWorkspace(f.backup,f.target),/changed during restore/);assert.equal(fs.existsSync(f.target),false);}finally{fs.copyFileSync=originalCopy;cleanup(f)}});

test('linked backup media directory cannot read outside the backup',()=>{const f=fixture();try{backupWorkspace(f.source,f.backup);const media=path.join(f.backup,'media'),external=path.join(f.root,'external');fs.renameSync(media,external);fs.symlinkSync(external,media,process.platform==='win32'?'junction':'dir');assert.throws(()=>restoreWorkspace(f.backup,f.target),/escapes/);assert.equal(fs.existsSync(f.target),false);fs.unlinkSync(media);}finally{cleanup(f)}});
