import './BackgroundGuide.css';
type Props={canAuto:boolean;autoReason?:string;drawing:boolean;pointCount:number;onAuto:()=>void;onDraw:()=>void;onFindEdges:()=>void;onUndoPoint:()=>void;onCancelDraw:()=>void;range:string;tooLong:boolean;selected:boolean;canSelect:boolean;canRemove:boolean;selectionTool:string;canTrack:boolean;canReview:boolean;reviewed:boolean;ready:boolean;hasGaps:boolean;prompt:string;canGenerate:boolean;hasVideo:boolean;assetName:string;onSelect:()=>void;onRemove:()=>void;onTrack:()=>void;onPlay:()=>void;onReview:(value:boolean)=>void;onPrompt:(value:string)=>void;onGenerate:()=>void;onUpload:()=>void;onBuild:()=>void};
export function BackgroundGuide(p:Props){return <div className="background-guide" aria-label="Change background in three steps">
 <p className="background-rule"><span aria-hidden="true">●</span> Yellow = keep this object. Unselected areas = new background.</p>
 <p className="background-next" role="status">{p.drawing?'Next: draw around the object, then find its edges.':!p.selected?'Next: choose how to select the object.':!p.reviewed?'Next: follow the object, play the clip, then check the box.':!p.ready?'The selection does not cover this clip yet. Follow the object again.':!p.prompt.trim()?'Next: describe your new background or choose your own video.':'Ready to review the price.'}</p>
 <section><h3><b>1</b> Choose what stays</h3><div className="background-select-methods"><button disabled={!p.canAuto} onClick={p.onAuto}>Auto background</button><button disabled={!p.canSelect} aria-pressed={p.selectionTool==='include'} onClick={p.onSelect}>Click object</button><button aria-pressed={p.drawing} onClick={p.onDraw}>Draw around object</button></div><p className="background-hint">Auto finds the main object on this frame. Check it, then follow it through the clip.</p>{!p.canAuto&&<p className="background-hint">{p.autoReason||'Auto selection is not installed. Use Click object or Draw around object.'}</p>}{p.drawing&&<div className="background-drawing"><p>Click at least 3 points around the object. {p.pointCount} points added.</p><button className="primary wide" disabled={!p.canSelect||p.pointCount<3} onClick={p.onFindEdges}>Find edges with SAM</button><div className="background-select-methods"><button disabled={!p.pointCount} onClick={p.onUndoPoint}>Undo last point</button><button onClick={p.onCancelDraw}>Cancel drawing</button></div></div>}<details><summary>Fix the selection</summary><button className="wide" disabled={!p.canRemove} aria-pressed={p.selectionTool==='exclude'} onClick={p.onRemove}>Remove from selection</button><p className="background-hint">For a handle or opening, choose Remove from selection, then click inside the hole.</p>{p.selected&&!p.canRemove&&<p className="background-hint">Choose Click object, then click the object once to start correcting this frame.</p>}</details></section>
 <section><h3><b>2</b> Follow it through the clip</h3><p className="background-range">{p.range}</p><button className="wide" disabled={!p.canTrack} onClick={p.onTrack}>Follow object through this clip</button>{p.tooLong&&<p className="background-warning">This clip is too long. Shorten it to 10 seconds or less.</p>}<button className="wide" disabled={!p.canReview} onClick={p.onPlay}>Play and check selection</button><label><input type="checkbox" checked={p.reviewed} disabled={!p.canReview} onChange={e=>p.onReview(e.target.checked)}/>The object stays selected, including around holes</label>{p.hasGaps&&<p className="background-warning">Some moments could not be followed. Those moments keep the original background.</p>}</section>
 <section><h3><b>3</b> Choose a new background</h3><label htmlFor="background-prompt">Describe the background</label><textarea id="background-prompt" rows={3} value={p.prompt} onChange={e=>p.onPrompt(e.target.value)} placeholder="A sunny beach with gentle waves"/><div className="background-examples">{['Underwater','Studio backdrop'].map(text=><button key={text} onClick={()=>p.onPrompt(text)}>{text}</button>)}</div><button className="primary wide" disabled={!p.canGenerate} onClick={p.onGenerate}>Review price and preview</button><p className="background-hint">See the price first. Your original stays saved.</p><details><summary>Use my own background video</summary><button className="wide" onClick={p.onUpload}>{p.hasVideo?'Change background video':'Choose background video'}</button>{p.assetName&&<p>{p.assetName}</p>}<p className="background-hint">Match the selected clip length, or use a full-length background video. No generation charge.</p><button className="wide" disabled={!p.ready||!p.hasVideo} onClick={p.onBuild}>Preview with my video</button></details></section>

 </div>}
