import {useEffect,useState} from 'react';
type Batch={canApprove?:boolean;blockedReason?:string;availableBudget?:number;createdAt:string;id:string;total:number;hold:number;baseRevisionId:string;plans:{instruction:string;start:number;end:number;route:{estimatedUsd:number;label:string}}[];jobIds:string[];jobs?:{id:string;status:string;error?:string;candidateId?:string;version:number}[]};
export function BatchVariations({projectId,revision,start,end,quality,referenceImageId,disabled,onResults}:{projectId:string;revision:string;start:number;end:number;quality:string;referenceImageId?:string;disabled:boolean;onResults:()=>void}){
 const [prompts,setPrompts]=useState(['','']),[batches,setBatches]=useState<Batch[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const url=`/api/projects/${projectId}/batches`;
 useEffect(()=>{let active=true;const load=()=>fetch(url).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Cannot load batches');if(active)setBatches(d)}).catch(e=>{if(active)setError(e.message)});void load();const timer=setInterval(load,5000);return()=>{active=false;clearInterval(timer)}},[url]);
 async function action(path:string,body:unknown){if(busy||disabled)return;setBusy(true);setError('');try{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'Batch request failed');setBatches(old=>[d,...old.filter(b=>b.id!==d.id)])}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section className="conversation-command-menu"><h3>Batch variations</h3><p>Compare 2–3 picture edits on this range. Each version changes the entire picture inside its range. For object-only changes, use the reviewed object workflow.</p>{prompts.map((p,i)=><label key={i}>Version {i+1}<textarea maxLength={3000} value={p} disabled={busy||disabled} onChange={e=>setPrompts(old=>old.map((v,n)=>i===n?e.target.value:v))}/></label>)}<button type="button" disabled={busy||disabled} onClick={()=>setPrompts(p=>p.length===2?[...p,'']:p.slice(0,2))}>{prompts.length===2?'Add third version':'Remove third version'}</button><button type="button" disabled={busy||disabled||prompts.some(p=>!p.trim())} onClick={()=>void action(url,{prompts,start,end,quality,baseRevisionId:revision,referenceImageId})}>Review combined cost</button>{busy&&<p role="status">Preparing batch…</p>}{error&&<p role="alert">{error}</p>}{batches.slice().sort((a,b)=>b.createdAt.localeCompare(a.createdAt)).map(b=><article className="conversation-plan" key={b.id}><h3>{b.plans.length} variations · estimated ${b.total.toFixed(2)}</h3><p>Budget hold ${b.hold.toFixed(2)}. Final billing may differ; fresh quotes are checked before submission. Versions run separately and can fail independently. Review or recover each result in Activity.</p>{b.plans.map((p,i)=><p key={i}>{i+1}. {p.instruction} · {p.start.toFixed(2)}–{p.end.toFixed(2)}s · {p.route.label} · ${p.route.estimatedUsd.toFixed(2)}</p>)}{b.jobIds.length?<><ul>{b.jobs?.map(j=><li key={j.id}><strong>Version {j.version}: {j.status}</strong>{j.error&&<p>{j.error}</p>}{j.candidateId&&<a href={`/review?project=${encodeURIComponent(projectId)}&candidate=${encodeURIComponent(j.candidateId)}`} target="_blank" rel="noreferrer">Compare version {j.version} with original</a>}</li>)}</ul><button type="button" onClick={onResults}>Open saved alternatives</button></>:<><p>Unreserved workspace budget: ${(b.availableBudget??0).toFixed(2)} · not a provider balance.</p>{b.blockedReason&&<p role="status">{b.blockedReason}</p>}<button type="button" disabled={busy||disabled||!b.canApprove||b.baseRevisionId!==revision} onClick={()=>void action(`${url}/${b.id}/run`,{confirmed:true})}>Approve all {b.plans.length} generations</button></>}</article>)}</section>
}
