import {useEffect,useState} from 'react';
type Preset={deleted?:boolean;projectId?:string;projectName?:string;id:string;name:string;instructions:string;referenceImageId?:string;referenceImage?:{url:string;name:string}};
export function BrandPresets({projectId,referenceImageId,disabled,onUse}:{projectId:string;referenceImageId?:string;disabled:boolean;onUse:(p:Preset)=>void}){
 const [editing,setEditing]=useState(false),[catalog,setCatalog]=useState<Preset[]>([]),[copyKey,setCopyKey]=useState(''),[showDeleted,setShowDeleted]=useState(false);
 const [items,setItems]=useState<Preset[]>([]),[name,setName]=useState(''),[instructions,setInstructions]=useState(''),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reload,setReload]=useState(0);
 useEffect(()=>{let active=true;setBusy(true);fetch(`/api/projects/${projectId}/brand-presets`).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Could not load presets');if(active){setItems(d);setError('')}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setBusy(false)});return()=>{active=false}},[projectId,reload]);
 async function save(){if(busy||disabled)return;setBusy(true);setError('');try{const r=await fetch(`/api/projects/${projectId}/brand-presets`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,instructions,referenceImageId})});const d=await r.json();if(!r.ok)throw Error(d.error||'Could not save preset');setItems(old=>[...old,d]);setSelected(d.id);setName('');setInstructions('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function mutate(path:string,body:unknown){if(busy||disabled)return;setBusy(true);setError('');try{const r=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'Preset could not be updated');setItems(old=>[...old.filter(x=>x.id!==d.id),d]);setSelected(d.id);setEditing(false)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function loadCatalog(){setBusy(true);setError('');try{const r=await fetch('/api/brand-presets');const d=await r.json();if(!r.ok)throw Error(d.error||'Could not load styles');setCatalog(d.filter((p:Preset)=>p.projectId!==projectId))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 const picked=items.find(p=>p.id===selected);
 return <section className="conversation-command-menu"><h3>Brand presets</h3><p>Manage project styles or copy one from another project. Copies are independent.</p>{error&&<p role="alert">{error} <button type="button" onClick={()=>setReload(x=>x+1)} disabled={busy}>Reload presets</button></p>}
 <label>Saved style<select aria-label="Saved brand preset" value={selected} disabled={disabled||busy} onChange={e=>{setSelected(e.target.value);setEditing(false)}}><option value="">Choose a preset</option>{items.filter(p=>showDeleted||!p.deleted).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label>
 <label><input type="checkbox" checked={showDeleted} onChange={e=>setShowDeleted(e.target.checked)}/> Show deleted presets</label>{picked&&<article className="conversation-plan"><strong>{picked.name}</strong><p style={{whiteSpace:'pre-wrap'}}>{picked.instructions}</p>{picked.referenceImage&&<img width="100" src={picked.referenceImage.url} alt={`Preset reference: ${picked.referenceImage.name}`}/>}<p>{picked.referenceImage?'This will replace the reference attached to your current draft.':'Your current reference image will stay attached.'} Nothing runs until you send and confirm the edit plan.</p><button type="button" disabled={disabled||busy||picked.deleted} onClick={()=>onUse(picked)}>Use preset in draft</button><button type="button" disabled={disabled||busy||picked.deleted} onClick={()=>{setEditing(true);setName(picked.name);setInstructions(picked.instructions)}}>Edit preset</button><button type="button" disabled={disabled||busy} onClick={()=>void mutate(`/api/projects/${projectId}/brand-presets/${picked.id}`,{deleted:!picked.deleted})}>{picked.deleted?'Restore preset':'Delete preset'}</button><small>Deleted presets can be restored here.</small>
 {editing&&<div><label>Edit name<input value={name} maxLength={60} onChange={e=>setName(e.target.value)}/></label><label>Edit instructions<textarea value={instructions} maxLength={1500} onChange={e=>setInstructions(e.target.value)}/></label><button type="button" disabled={disabled||busy||!name.trim()||!instructions.trim()} onClick={()=>void mutate(`/api/projects/${projectId}/brand-presets/${picked.id}`,{name,instructions})}>Save changes</button>{referenceImageId&&<button type="button" disabled={disabled||busy} onClick={()=>void mutate(`/api/projects/${projectId}/brand-presets/${picked.id}`,{name,instructions,referenceImageId})}>Save with attached image</button>}{picked.referenceImageId&&<button type="button" disabled={disabled||busy} onClick={()=>void mutate(`/api/projects/${projectId}/brand-presets/${picked.id}`,{name,instructions,referenceImageId:''})}>Save without reference</button>}<button type="button" onClick={()=>setEditing(false)}>Cancel editing</button></div>}</article>}
 {busy&&<p role="status">Updating presets…</p>}
 <details><summary>Copy from another project</summary><button type="button" disabled={disabled||busy} onClick={()=>void loadCatalog()}>Load my project presets</button><select aria-label="Preset to copy" value={copyKey} onChange={e=>setCopyKey(e.target.value)}><option value="">Choose a style to copy</option>{catalog.map(p=><option key={p.id} value={p.id}>{p.projectName} · {p.name}</option>)}</select><button type="button" disabled={disabled||busy||!catalog.some(p=>p.id===copyKey)} onClick={()=>{const p=catalog.find(p=>p.id===copyKey)!;void mutate(`/api/projects/${projectId}/brand-presets/copy`,{projectId:p.projectId,presetId:p.id})}}>Copy preset and reference</button></details>
 <details><summary>Save a new preset</summary><label>Preset name<input maxLength={60} value={name} onChange={e=>setName(e.target.value)} disabled={disabled||busy}/></label><label>Style instructions<textarea maxLength={1500} value={instructions} onChange={e=>setInstructions(e.target.value)} disabled={disabled||busy} placeholder="Warm natural lighting, matte materials, muted colorsâ€¦"/></label><p>{referenceImageId?'Includes the image attached to your current message.':'Optional: attach an image to your message first to include it.'}</p><button type="button" disabled={disabled||busy||!name.trim()||!instructions.trim()} onClick={()=>void save()}>{busy?'Workingâ€¦':'Save preset'}</button></details></section>
}
