import {useEffect,useRef,useState} from 'react';
import type {CandidateEvidence} from './CandidateQuality';
import './CandidateLibrary.css';
type Alternative=CandidateEvidence&{id:string,url:string,label?:string,name:string,favorite:boolean,createdAt?:string,baseRevisionId:string,canCompare:boolean,canApply:boolean,dismissedAt?:string,maskReviewUrl?:string,start?:number,end?:number};
async function request(url:string,body?:unknown){const response=await fetch(url,{...(body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})});const data=await response.json();if(!response.ok)throw Error(data.error||'Could not load saved alternatives.');return data;}
export function CandidateLibrary({projectId,onClose,onReview}:{projectId:string,onClose:()=>void,onReview:(candidate:Alternative)=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const [items,setItems]=useState<Alternative[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[pending,setPending]=useState(''),[favorites,setFavorites]=useState(false),[preview,setPreview]=useState<Alternative|null>(null),[editing,setEditing]=useState(''),[name,setName]=useState(''),[reload,setReload]=useState(0);
 useEffect(()=>{dialog.current?.showModal();return()=>dialog.current?.close()},[]);
 useEffect(()=>{let active=true;setLoading(true);request(`/api/projects/${projectId}/candidates`).then(data=>{if(active){setItems(data);setError('')}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[projectId,reload]);
 async function update(item:Alternative,changes:{name?:string,favorite?:boolean}){if(pending)return;setPending(item.id);setError('');try{const next=await request(`/api/projects/${projectId}/candidates/${item.id}/details`,changes);setItems(old=>old.map(c=>c.id===next.id?next:c));setEditing('');}catch(e){setError((e as Error).message)}finally{setPending('')}}
 const visible=items.filter(c=>!favorites||c.favorite).sort((a,b)=>Number(b.favorite)-Number(a.favorite)||String(b.createdAt||'').localeCompare(String(a.createdAt||'')));
 return <dialog ref={dialog} className="candidate-library" aria-labelledby="alternatives-title" onCancel={event=>{event.preventDefault();if(!pending)onClose()}}><header><div><h2 id="alternatives-title">Saved alternatives</h2><p>Every finished candidate stays here—even discarded previews. Reopening never generates again.</p></div><button disabled={!!pending} onClick={onClose} aria-label="Close saved alternatives">Close</button></header><label><input type="checkbox" checked={favorites} onChange={e=>setFavorites(e.target.checked)}/> Favorites only</label>{error&&<div role="alert"><p>{error}</p><button disabled={!!pending} onClick={()=>setReload(v=>v+1)}>Reload alternatives</button></div>}{loading?<p role="status">Loading alternatives…</p>:visible.length===0?<p>{favorites?'No favorites yet. Mark a candidate as a favorite to find it here.':'Create a preview to start collecting alternatives.'}</p>:<ul>{visible.map(item=><li key={item.id}><div className="alternative-heading"><strong>{item.name||item.label||'Candidate'}</strong><span>{item.canApply?'Available for this revision':item.canCompare?'Previously applied · comparison available':'Different revision · saved preview'}</span></div><small>{item.createdAt?new Date(item.createdAt).toLocaleString():''}{item.dismissedAt?' · Previously discarded':''}</small>{editing===item.id?<form onSubmit={e=>{e.preventDefault();void update(item,{name})}}><label>Alternative name<input autoFocus maxLength={80} value={name} onChange={e=>setName(e.target.value)}/></label><button disabled={!!pending}>Save name</button><button type="button" disabled={!!pending} onClick={()=>setEditing('')}>Cancel rename</button></form>:null}<div className="alternative-actions"><a href={`/review?project=${encodeURIComponent(projectId)}&candidate=${encodeURIComponent(item.id)}`} target="_blank" rel="noreferrer">Open before / after page</a><button disabled={!!pending} onClick={()=>void update(item,{favorite:!item.favorite})}>{item.favorite?'Remove favorite':'Favorite'}</button><button disabled={!!pending} onClick={()=>{setEditing(item.id);setName(item.name||'')}}>Rename</button><button disabled={!!pending} onClick={()=>setPreview(item)}>Preview saved video</button><button disabled={!!pending||!item.canCompare} onClick={()=>{onReview({...item,label:item.name||item.label});onClose()}}>Compare with current</button></div></li>)}</ul>}{preview&&<section className="alternative-preview" aria-label="Saved video preview"><h3>{preview.name||preview.label||'Candidate'}</h3><video key={preview.id} src={preview.url} controls playsInline preload="metadata"/>{!preview.canApply&&<p>This video belongs to an older or already applied revision. Previewing does not replace your current work.</p>}<button onClick={()=>setPreview(null)}>Close video preview</button></section>}</dialog>;
}
