import {ReviewNotes} from './ReviewNotes';
import {useEffect,useRef,useState} from 'react';
import {StackedComparison} from './StackedComparison';
import {CandidateQuality,type CandidateEvidence} from './CandidateQuality';
import './ComparisonPage.css';
type Comparison=CandidateEvidence&{projectName:string;candidateName:string;originalUrl:string;candidateUrl:string;duration:number};
export function ComparisonPage(){
 const [data,setData]=useState<Comparison|null>(null),[error,setError]=useState(''),[time,setTime]=useState(0),[playing,setPlaying]=useState(false),[reload,setReload]=useState(0);const master=useRef<HTMLVideoElement>(null);
 useEffect(()=>{const query=new URLSearchParams(location.search),pid=query.get('project'),cid=query.get('candidate');const abort=new AbortController();if(!pid||!cid){setError('Choose a candidate from Saved alternatives.');return;}setError('');fetch(`/api/projects/${encodeURIComponent(pid)}/candidates/${encodeURIComponent(cid)}/comparison`,{signal:abort.signal}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Comparison unavailable');setData(d)}).catch(e=>{if(!abort.signal.aborted)setError(e.message)});return()=>abort.abort()},[reload]);
 return <main className="comparison-page"><header><a href="/studio">← Back to studio</a><span>Private workspace review · no generation charge</span></header><h1>{data?.candidateName||'Before / after'}</h1><p>{data?.projectName} · Original means the exact revision used to create this candidate. Reviewing does not apply an edit.</p>{error&&<div role="alert"><p>{error}</p><button onClick={()=>setReload(x=>x+1)}>Retry loading</button></div>}{!data&&!error&&<p role="status">Loading comparison…</p>}{data&&<><StackedComparison originalLabel="Original revision" key={reload} current={data.originalUrl} candidate={data.candidateUrl} master={master} time={time} onTime={setTime} onPlaying={setPlaying} onError={()=>setError('A comparison video could not load. Check the connection and retry.')}/><div className="comparison-controls"><button disabled={!!error} onClick={()=>{const v=master.current;if(!v)return;if(v.paused)void v.play().catch(()=>setError('Playback could not start. Retry loading.'));else v.pause()}}>{playing?'Pause':'Play comparison'}</button><label>Position<input aria-label="Comparison playhead" type="range" min="0" max={data.duration||0} step="0.033333" value={time} onChange={e=>{const t=Number(e.target.value);if(master.current)master.current.currentTime=t;setTime(t)}}/></label><span>{time.toFixed(2)}s / {data.duration.toFixed(2)}s</span></div><CandidateQuality candidate={data}/><ReviewNotes time={time} onPause={()=>master.current?.pause()} onSeek={t=>{if(master.current)master.current.currentTime=t;setTime(t)}}/><p>This link requires access to this workspace. It is not a public share link.</p></>}</main>
}
