import {useEffect,useRef,useState} from 'react';
import './CandidateLibrary.css';
type Item={id:string;kind:string;projectId?:string;projectName?:string;prompt:string;status:string;error?:string;billing?:string;createdAt?:string;available:boolean;url?:string};
export function GenerationLibrary({onClose,onOpen}:{onClose:()=>void;onOpen:(id:string)=>void}){
 const dialog=useRef<HTMLDialogElement>(null);const [items,setItems]=useState<Item[]>([]),[query,setQuery]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(true),[preview,setPreview]=useState<Item|null>(null);
 useEffect(()=>{dialog.current?.showModal();const abort=new AbortController();fetch('/api/generation-library',{signal:abort.signal}).then(async r=>{if(!r.ok)throw Error('Could not load saved generations.');setItems(await r.json());}).catch(e=>{if(e.name!=='AbortError')setError(e.message)}).finally(()=>setLoading(false));return()=>{abort.abort();dialog.current?.close();}},[]);
 const visible=items.filter(i=>[i.prompt,i.projectName,i.kind,i.status].join(' ').toLowerCase().includes(query.toLowerCase()));
 return <dialog ref={dialog} className="candidate-library" onCancel={e=>{e.preventDefault();onClose()}} aria-label="Generation library"><header><div><h2>Generation library</h2><p>Originals, raw generations and finished edits across your projects. Previewing never generates again.</p></div><button onClick={onClose}>Close library</button></header><label>Find a generation<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search prompt, project or status"/></label>{error&&<p role="alert">{error}</p>}{loading?<p role="status">Loading saved generations…</p>:<p>{visible.length} saved records · Files are stored in this workspace, not a cloud backup.</p>}{preview&&<section className="alternative-preview"><h3>{preview.prompt||preview.kind}</h3><video key={preview.id} src={preview.url} controls playsInline preload="metadata"/><button onClick={()=>setPreview(null)}>Close preview</button></section>}<ul>{visible.map(i=><li key={i.id}><div className="alternative-heading"><strong>{i.kind} · {i.projectName||'Unattached request'}</strong><span>{i.status}{i.available&&i.status==='failed'?' · footage retained':''}</span></div><small>{i.createdAt?new Date(i.createdAt).toLocaleString():''}</small><p>{i.prompt||'No prompt recorded'}</p>{i.error&&<details><summary>Request details</summary><p>{i.error}</p></details>}{i.billing&&<p>{i.billing}</p>}<div className="alternative-actions">{i.available?<><button onClick={()=>setPreview(i)}>Preview saved footage</button><a href={i.url} download>Download</a></>:<span>No local output available</span>}{i.projectId&&<button onClick={()=>onOpen(i.projectId!)}>Open project</button>}</div></li>)}</ul></dialog>;
}
