import {useEffect,useMemo,useRef,useState} from 'react';
import './MarkersPanel.css';

export type Marker={id:string;label:string;note:string;start:number;end:number;baseRevisionId:string;createdAt:string;archived:boolean};
type Props={project:{id:string;duration:number;fps:number;activeRevisionId:string}|null;open:boolean;onClose:()=>void;start:number;end:number;time:number;busy:boolean;onSelect:(marker:Marker)=>void;onMarkersChange?:(markers:Marker[])=>void};

async function request<T>(url:string,body?:unknown,signal?:AbortSignal):Promise<T>{
 const response=await fetch(url,body===undefined?{signal}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body),signal});
 const data=await response.json();
 if(response.status===401){window.location.reload();throw new Error('Your session expired. Please sign in again.');}
 if(!response.ok)throw new Error(data.error||data.message||'Saved moments could not be updated.');
 return data;
}
const timecode=(value:number)=>`${Math.floor(value/60).toString().padStart(2,'0')}:${(value%60).toFixed(2).padStart(5,'0')}`;

export function MarkersPanel({project,open,onClose,start,end,time,busy,onSelect,onMarkersChange}:Props){
 const [markers,setMarkers]=useState<Marker[]>([]),[kind,setKind]=useState<'range'|'point'>('range'),[label,setLabel]=useState(''),[note,setNote]=useState(''),[query,setQuery]=useState(''),[showArchived,setShowArchived]=useState(false),[loading,setLoading]=useState(false),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const requestVersion=useRef(0),pendingCreate=useRef<{signature:string;key:string}|null>(null),markersRef=useRef<Marker[]>([]),mutations=useRef(new Set<AbortController>()),projectContext=useRef<{id:string|null;version:number}>({id:null,version:0});
 if(projectContext.current.id!==(project?.id??null))projectContext.current={id:project?.id??null,version:projectContext.current.version+1};
 const publish=(next:Marker[])=>{markersRef.current=next;setMarkers(next);onMarkersChange?.(next)};
 useEffect(()=>{const context=projectContext.current;for(const controller of mutations.current)controller.abort();mutations.current.clear();requestVersion.current++;pendingCreate.current=null;markersRef.current=[];setMarkers([]);onMarkersChange?.([]);setKind('range');setLabel('');setNote('');setQuery('');setShowArchived(false);setError('');setMessage('');setSaving(false);if(!project){setLoading(false);return}const version=++requestVersion.current,controller=new AbortController();setLoading(true);request<Marker[]>(`/api/projects/${project.id}/markers`,undefined,controller.signal).then(next=>{if(version!==requestVersion.current||projectContext.current!==context)return;publish(next)}).catch(reason=>{if(version!==requestVersion.current||projectContext.current!==context||reason.name==='AbortError')return;setError(reason.message)}).finally(()=>{if(version===requestVersion.current&&projectContext.current===context)setLoading(false)});return()=>{controller.abort();requestVersion.current++;for(const pending of mutations.current)pending.abort();mutations.current.clear()}},[project?.id]);
 useEffect(()=>{pendingCreate.current=null},[label,note,kind,start,end,time,project?.id,project?.activeRevisionId]);
 const visible=useMemo(()=>{const needle=query.trim().toLowerCase();return markers.filter(marker=>(showArchived||!marker.archived)&&(!needle||`${marker.label} ${marker.note}`.toLowerCase().includes(needle))).sort((a,b)=>a.start-b.start||a.createdAt.localeCompare(b.createdAt))},[markers,query,showArchived]);
 if(!open)return null;
 const create=async(event:React.FormEvent)=>{event.preventDefault();if(!project||saving)return;const context=projectContext.current,controller=new AbortController();mutations.current.add(controller);const markerStart=kind==='point'?time:start,markerEnd=kind==='point'?time:end;const signature=JSON.stringify([project.id,project.activeRevisionId,label.trim(),note.trim(),markerStart,markerEnd]);if(pendingCreate.current?.signature!==signature)pendingCreate.current={signature,key:crypto.randomUUID()};setSaving(true);setError('');setMessage('');try{const marker=await request<Marker>(`/api/projects/${project.id}/markers`,{label,note,start:markerStart,end:markerEnd,baseRevisionId:project.activeRevisionId,idempotencyKey:pendingCreate.current.key},controller.signal);if(projectContext.current!==context)return;const next=[...markersRef.current.filter(item=>item.id!==marker.id),marker];publish(next);pendingCreate.current=null;setLabel('');setNote('');setMessage(marker.start===marker.end?'Point saved at the playhead.':'Selected range saved.')}catch(reason){if(projectContext.current===context&&(reason as Error).name!=='AbortError')setError((reason as Error).message)}finally{mutations.current.delete(controller);if(projectContext.current===context)setSaving(false)}};
 const update=async(marker:Marker,archived:boolean)=>{if(!project||saving)return;const context=projectContext.current,controller=new AbortController();mutations.current.add(controller);setSaving(true);setError('');setMessage('');try{const changed=await request<Marker>(`/api/projects/${project.id}/markers/${marker.id}/update`,{archived},controller.signal);if(projectContext.current!==context)return;const next=markersRef.current.map(item=>item.id===changed.id?changed:item);publish(next);setMessage(archived?'Moment archived. You can restore it here.':'Moment restored.')}catch(reason){if(projectContext.current===context&&(reason as Error).name!=='AbortError')setError((reason as Error).message)}finally{mutations.current.delete(controller);if(projectContext.current===context)setSaving(false)}};
 return <aside className="markers-panel" aria-labelledby="markers-title">
  <header className="markers-header"><div><span className="markers-kicker">Project memory</span><h2 id="markers-title">Saved moments</h2></div><button className="markers-close" type="button" aria-label="Close saved moments" onClick={onClose}>×</button></header>
  {!project?<div className="markers-empty"><strong>Choose a project first.</strong><span>Saved moments stay attached to one project.</span></div>:<>
   <form className="marker-form" onSubmit={create}>
    <fieldset disabled={busy||saving}><legend>Save a moment</legend><div className="marker-kind" role="radiogroup" aria-label="Moment type"><label><input type="radio" name="marker-kind" checked={kind==='range'} onChange={()=>setKind('range')}/>Selected range <span>{timecode(start)}–{timecode(end)}</span></label><label><input type="radio" name="marker-kind" checked={kind==='point'} onChange={()=>setKind('point')}/>Point at playhead <span>{timecode(time)}</span></label></div>
    <label className="marker-field">Name<input required maxLength={80} value={label} onChange={event=>setLabel(event.target.value)} placeholder="Opening beat"/></label>
    <label className="marker-field">Note <span>optional</span><textarea maxLength={1000} rows={2} value={note} onChange={event=>setNote(event.target.value)} placeholder="What makes this moment useful?"/></label>
    <button className="marker-save" type="submit" disabled={!label.trim()||busy||saving}>{saving?'Saving…':'Save moment'}</button></fieldset>
   </form>
   <div className="marker-tools"><label className="marker-search"><span className="sr-only">Search saved moments</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search names and notes"/></label><label className="marker-archived"><input type="checkbox" checked={showArchived} onChange={event=>setShowArchived(event.target.checked)}/>Show archived</label></div>
   {error&&<p className="marker-feedback marker-error" role="alert">{error}</p>}{message&&<p className="marker-feedback" role="status">{message}</p>}
   <div className="marker-list" aria-live="polite">{loading?<p className="markers-empty">Loading saved moments…</p>:visible.length===0?<p className="markers-empty">{query?'No moments match this search.':showArchived?'No saved moments yet.':'No active moments yet.'}</p>:visible.map(marker=><article className={`marker-card${marker.archived?' archived':''}`} key={marker.id}><button className="marker-jump" type="button" onClick={()=>onSelect(marker)} disabled={busy}><span className="marker-time">{marker.start===marker.end?timecode(marker.start):`${timecode(marker.start)}–${timecode(marker.end)}`}</span><strong>{marker.label}</strong>{marker.note&&<span className="marker-note">{marker.note}</span>}<span className="marker-meta">{marker.baseRevisionId===project.activeRevisionId?'Current revision':'Earlier revision'} · {new Date(marker.createdAt).toLocaleDateString()}</span></button><button className="marker-archive-button" type="button" disabled={busy||saving} onClick={()=>void update(marker,!marker.archived)}>{marker.archived?'Restore':'Archive'}</button></article>)}</div>
  </>}
 </aside>;
}
