import {useEffect,useRef,useState} from 'react';
import {frameTime,windowAround,type TimeRange} from './editor-controls';
import './PrecisionTimeline.css';
type Marker={id:string,label:string,start:number,end:number,archived:boolean};
type Props={project:{id:string,name:string,duration:number,fps:number,thumbnailUrl?:string,waveform?:number[]}|null;start:number;end:number;time:number;locked:boolean;markers:Marker[];onSeek:(time:number)=>void;onSelection:(start:number,end:number)=>void;onMarker:(marker:Marker)=>void;onMark:(edge:'in'|'out'|'frame')=>void;onOpenMarkers:()=>void};
const tc=(v:number)=>`${Math.floor(v/60).toString().padStart(2,'0')}:${(v%60).toFixed(2).padStart(5,'0')}`;
export function PrecisionTimeline({project,start,end,time,locked,markers,onSeek,onSelection,onMarker,onMark,onOpenMarkers}:Props){
 const duration=project?.duration??1,fps=project?.fps??30;const [window,setWindow]=useState<TimeRange>({start:0,end:duration});const detail=useRef<HTMLDivElement>(null);const cleanup=useRef<()=>void>(()=>{});
 useEffect(()=>()=>cleanup.current(),[]);
 useEffect(()=>{setWindow({start:0,end:duration})},[project?.id,duration]);
 const span=Math.max(1/fps,window.end-window.start),percent=(t:number)=>(t-window.start)/span*100;
 function zoom(factor:number){setWindow(windowAround(time,Math.max(4/fps,Math.min(duration,span*factor)),duration))}
 function selectEdge(event:React.PointerEvent<HTMLButtonElement>,edge:'start'|'end'){
  if(!project||locked)return;cleanup.current();event.preventDefault();event.currentTarget.setPointerCapture(event.pointerId);
  const move=(ev:PointerEvent)=>{if(!detail.current)return;const r=detail.current.getBoundingClientRect();const t=frameTime(window.start+(ev.clientX-r.left)/r.width*span,duration,fps);if(edge==='start')onSelection(Math.max(0,Math.min(end-1/fps,t)),end);else onSelection(start,Math.min(duration,Math.max(start+1/fps,t)))};
  const stop=()=>{globalThis.removeEventListener('pointermove',move);globalThis.removeEventListener('pointerup',stop);globalThis.removeEventListener('pointercancel',stop)};
  cleanup.current=stop;globalThis.addEventListener('pointermove',move);globalThis.addEventListener('pointerup',stop);globalThis.addEventListener('pointercancel',stop);
 }
 function edgeKey(e:React.KeyboardEvent,edge:'start'|'end'){if(locked||!project||!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();e.stopPropagation();const delta=(e.key==='ArrowRight'?1:-1)*(e.shiftKey?10:1)/fps;if(edge==='start')onSelection(frameTime(Math.max(0,Math.min(end-1/fps,start+delta)),duration,fps),end);else onSelection(start,frameTime(Math.min(duration,Math.max(start+1/fps,end+delta)),duration,fps))}
 const a=Math.max(window.start,start),b=Math.min(window.end,end),wave=project?.waveform??[];
 return <section className="precision-timeline" aria-label="Precision timeline">
  <div className="precision-title"><div><strong>Your timeline</strong><span>{project?`${Math.round((end-start)*fps)} frame${Math.round((end-start)*fps)===1?'':'s'} selected`:'Import a video to begin'}</span></div><button onClick={onOpenMarkers} disabled={!project}>Saved moments <kbd>M</kbd></button></div>
  <div className="precision-actions"><div><button onClick={()=>onMark('in')} disabled={!project||locked} title="Set selection start at playhead (I)">Set in <kbd>I</kbd></button><button onClick={()=>onMark('out')} disabled={!project||locked} title="Set selection end at playhead (O)">Set out <kbd>O</kbd></button><button onClick={()=>onMark('frame')} disabled={!project||locked}>One frame</button></div><div><button aria-label="Zoom out timeline" disabled={!project||span>=duration-.00001} onClick={()=>zoom(2)}>−</button><span className="mono">{(duration/span).toFixed(1)}×</span><button aria-label="Zoom in timeline" disabled={!project||span<=4/fps+.00001} onClick={()=>zoom(.5)}>+</button><button disabled={!project} onClick={()=>setWindow({start:0,end:duration})}>Fit</button><button disabled={!project} onClick={()=>setWindow(windowAround((start+end)/2,Math.max(4/fps,(end-start)*1.5),duration))}>Selection</button></div></div>
  <div className="timeline-overview"><span className="overview-range" style={{left:`${start/duration*100}%`,width:`${(end-start)/duration*100}%`}}/><span className="overview-window" style={{left:`${window.start/duration*100}%`,width:`${span/duration*100}%`}}/><input aria-label="Timeline overview playhead" type="range" min={0} max={duration} step={1/fps} value={time} disabled={!project} onChange={e=>{const t=+e.target.value;onSeek(t);if(t<window.start||t>window.end)setWindow(windowAround(t,span,duration))}}/></div>
  <div className="precision-detail" ref={detail}>
   <div className="precision-ruler">{Array.from({length:5},(_,i)=><span key={i}>{tc(window.start+span*i/4)}</span>)}</div>
   <button className="precision-film" aria-label="Seek in timeline" disabled={!project} style={project?.thumbnailUrl?{backgroundImage:`linear-gradient(#15201a44,#15201a99),url(${project.thumbnailUrl})`,backgroundSize:`100% 100%,${duration/span*100}% 100%`,backgroundPosition:`0 0,${window.start/Math.max(1e-6,duration-span)*100}% 0`}:undefined} onClick={e=>{const r=e.currentTarget.getBoundingClientRect();onSeek(frameTime(e.detail===0?window.start+span/2:window.start+(e.clientX-r.left)/r.width*span,duration,fps))}}><span>{project?.name??'No footage'}</span></button>
   <div className="precision-wave">{wave.length?<svg viewBox={`${window.start/duration*wave.length*4} 0 ${span/duration*wave.length*4} 32`} preserveAspectRatio="none" role="img" aria-label="Source audio waveform">{wave.map((v,i)=><rect key={i} x={i*4} y={16-Math.max(1,v*14)} width={2} height={Math.max(2,v*28)}/>)}</svg>:<span>Audio</span>}</div>
   {project&&<>{b>a&&<div className="precision-selected" style={{left:`${percent(a)}%`,width:`${percent(b)-percent(a)}%`}}/>}{start>=window.start&&start<=window.end&&<button className="precision-handle" style={{left:`${percent(start)}%`}} aria-label="Selection start" title={`Selection start ${tc(start)}`} disabled={locked} onPointerDown={e=>selectEdge(e,'start')} onKeyDown={e=>edgeKey(e,'start')}>Ⅰ</button>}{end>=window.start&&end<=window.end&&<button className="precision-handle end" style={{left:`${percent(end)}%`}} aria-label="Selection end" title={`Selection end ${tc(end)}`} disabled={locked} onPointerDown={e=>selectEdge(e,'end')} onKeyDown={e=>edgeKey(e,'end')}>Ⅰ</button>}{time>=window.start&&time<=window.end&&<div className="precision-playhead" style={{left:`${percent(time)}%`}}/>}{markers.filter(m=>!m.archived&&m.start>=window.start&&m.start<=window.end).map(m=><button key={m.id} className="timeline-marker" style={{left:`${Math.max(1.5,Math.min(98.5,percent(m.start)))}%`}} aria-label={`Go to saved moment: ${m.label}`} title={`${m.label} · ${tc(m.start)}`} onClick={()=>onMarker(m)}>◆</button>)}</>}
  </div>
  {span<duration-.00001&&<label className="timeline-pan"><span>Move detailed view</span><input type="range" min={0} max={duration-span} step={1/fps} value={window.start} onChange={e=>setWindow({start:+e.target.value,end:+e.target.value+span})}/></label>}
  <div className="precision-foot"><span className="mono">{tc(start)} — {tc(end)}</span><span>Yellow = selection · white = playhead</span></div>
 </section>;
}
