import {useEffect,useRef,useState} from 'react';
type Note={id:string;text:string;time:number};
export function ReviewNotes({time,onSeek,onPause}:{time:number;onSeek:(t:number)=>void;onPause:()=>void}){
 const q=new URLSearchParams(location.search),url=`/api/projects/${encodeURIComponent(q.get('project')||'')}/candidates/${encodeURIComponent(q.get('candidate')||'')}/notes`;
 const [notes,setNotes]=useState<Note[]>([]),[text,setText]=useState(''),[at,setAt]=useState<number|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[reload,setReload]=useState(0);const request=useRef<{signature:string,key:string}|null>(null);
 useEffect(()=>{let active=true;fetch(url).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Cannot load notes');if(active)setNotes(d)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[url,reload]);
 async function save(){if(busy||at===null||!text.trim())return;setBusy(true);setError('');const signature=JSON.stringify([at,text]);if(request.current?.signature!==signature)request.current={signature,key:crypto.randomUUID()};try{const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,time:at,key:request.current.key})});const d=await r.json();if(!r.ok)throw Error(d.error||'Cannot save note');setNotes(d);setText('');setAt(null);request.current=null}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <section><h2>Timestamped feedback</h2><button disabled={busy} onClick={()=>{onPause();setAt(time)}}>Note this moment · {time.toFixed(2)}s</button>{at!==null&&<div><label>Feedback at {at.toFixed(2)}s<textarea maxLength={1000} value={text} disabled={busy} onChange={e=>setText(e.target.value)}/></label><button disabled={busy||!text.trim()} onClick={()=>void save()}>{busy?'Saving…':'Save note'}</button><button disabled={busy} onClick={()=>setAt(null)}>Cancel</button></div>}{error&&<p role="alert">{error}<button onClick={()=>setReload(x=>x+1)}>Reload notes</button></p>}<ul>{notes.slice().sort((a,b)=>a.time-b.time).map(n=><li key={n.id}><button onClick={()=>{onPause();onSeek(n.time)}}>{n.time.toFixed(2)}s</button> <span style={{whiteSpace:'pre-wrap'}}>{n.text}</span></li>)}</ul><p>Notes belong to this candidate. They do not change the video or generate an edit.</p></section>
}
