import {useEffect,useRef,useState} from 'react';
import './SetupWizard.css';
type Settings={values:{REASONING_PROVIDER:string;LLM_BASE_URL:string;LLM_MODEL:string;HIGGSFIELD_TEST_BUDGET_USD?:string};configured:{LLM_API_KEY:boolean;TYPESAFE_API_KEY:boolean;HF_CREDENTIALS:boolean};readiness?:{assistant:boolean;video:boolean}};
function connected(s:Settings){return s.readiness??{assistant:s.values.REASONING_PROVIDER==='jev'?s.configured.TYPESAFE_API_KEY:!!(s.configured.LLM_API_KEY&&s.values.LLM_MODEL&&(s.values.REASONING_PROVIDER!=='openai-compatible'||s.values.LLM_BASE_URL)),video:s.configured.HF_CREDENTIALS};}
export function SetupWizard({onSaved}:{onSaved:()=>void}){
 const [data,setData]=useState<Settings|null>(null),[skipped,setSkipped]=useState(false),[provider,setProvider]=useState('jev'),[model,setModel]=useState(''),[address,setAddress]=useState(''),[assistantKey,setAssistantKey]=useState(''),[videoKey,setVideoKey]=useState(''),[budget,setBudget]=useState('0'),[busy,setBusy]=useState(false),[error,setError]=useState('');const dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const controller=new AbortController();fetch('/api/settings',{signal:controller.signal}).then(async r=>{if(!r.ok)return null;return r.json()}).then((s:Settings|null)=>{if(!controller.signal.aborted&&s?.values&&s.configured){setData(s);setProvider(s.values.REASONING_PROVIDER||'jev');setModel(s.values.LLM_MODEL||'');setAddress(s.values.LLM_BASE_URL||'');setBudget(s.values.HIGGSFIELD_TEST_BUDGET_USD||'0')}}).catch(()=>{});return()=>controller.abort()},[]);
 const ready=data?connected(data):null,open=!!ready&&(!ready.assistant||!ready.video)&&!skipped;
 useEffect(()=>{if(open)dialog.current?.showModal();else dialog.current?.close()},[open]);
 function skip(){setAssistantKey('');setVideoKey('');setSkipped(true)}
 async function save(){if(!data||!ready||busy)return;const patch:Record<string,string>={};
  if(!ready.assistant&&(assistantKey.trim()||provider!==data.values.REASONING_PROVIDER||model.trim()!==data.values.LLM_MODEL||address.trim()!==data.values.LLM_BASE_URL)){patch.REASONING_PROVIDER=provider;if(provider!=='jev'){patch.LLM_MODEL=model.trim();patch.LLM_BASE_URL=address.trim();}if(assistantKey.trim())patch[provider==='jev'?'TYPESAFE_API_KEY':'LLM_API_KEY']=assistantKey.trim();}
  if(!ready.video){if(videoKey.trim())patch.HF_CREDENTIALS=videoKey.trim();if(budget!== (data.values.HIGGSFIELD_TEST_BUDGET_USD||'0'))patch.HIGGSFIELD_TEST_BUDGET_USD=budget;}
  if(!Object.keys(patch).length){setError('Add a key, or choose Use local tools for now.');return;}
  setBusy(true);setError('');try{const response=await fetch('/api/settings',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(patch)});const result=await response.json();if(!response.ok)throw Error(result.error||'Could not save. Try again.');setData(result);setAssistantKey('');setVideoKey('');onSaved();if(connected(result).assistant&&connected(result).video)setSkipped(true);}catch(e){setError((e as Error).message)}finally{setBusy(false)}
 }
 if(!open)return null;
 return <dialog ref={dialog} className="setup-wizard" aria-labelledby="setup-title" onCancel={e=>{e.preventDefault();if(!busy)skip()}}><h2 id="setup-title">Connect your AI tools</h2><p>Add your own API keys to turn on AI features. You can still edit videos with local tools.</p><form onSubmit={e=>{e.preventDefault();void save()}}><fieldset disabled={busy}>
 {ready?.assistant?<p className="setup-connected">✓ Your assistant settings are saved.</p>:<section><h3>1. Editing assistant</h3><p>Turns your words into editing steps.</p><label>Assistant service<select value={provider} onChange={e=>{setProvider(e.target.value);setAssistantKey('');setModel('');setAddress('')}}><option value="jev">Jev / TypeSafe</option><option value="openai-compatible">OpenAI-compatible service</option><option value="anthropic">Anthropic</option><option value="gemini">Google Gemini</option></select></label>{provider!=='jev'&&<><label>Model name<input value={model} onChange={e=>setModel(e.target.value)} placeholder="Model name from your service" autoComplete="off"/></label>{provider==='openai-compatible'&&<label>API address<input type="url" value={address} onChange={e=>setAddress(e.target.value)} placeholder="https://your-service.example/v1" autoComplete="off"/></label>}</>}<label>Assistant API key<input type="password" value={assistantKey} onChange={e=>setAssistantKey(e.target.value)} autoComplete="new-password" spellCheck={false} placeholder="Paste your key"/></label></section>}
 {ready?.video?<p className="setup-connected">✓ Your video settings are saved.</p>:<section><h3>2. Video generation</h3><p>Creates new video with Higgsfield.</p><label>Higgsfield API credentials<input type="password" value={videoKey} onChange={e=>setVideoKey(e.target.value)} autoComplete="new-password" spellCheck={false} placeholder="key-id:key-secret"/></label><small>Paste the full key ID and secret, joined by a colon.</small><label>Video budget (USD)<input type="number" min="0" step="0.01" value={budget} onChange={e=>setBudget(e.target.value)}/></label><small>This sets this app’s spending allowance, not a credit purchase. Zero keeps paid generation off; local editing still works.</small></section>}
 <p className="setup-privacy">Keys stay on this server and are never shown again. Saving does not generate a video or use credits. Existing connections stay as they are.</p>{error&&<p role="alert">{error}</p>}<div className="setup-actions"><button type="submit" className="primary">{busy?'Saving…':'Save connections'}</button><button type="button" onClick={skip}>Use local tools for now</button></div></fieldset></form></dialog>
}
