import {useEffect,useRef,useState,type RefObject} from 'react';
export function StackedComparison({originalLabel='Current',sourceFrames,current,candidate,master,time,onTime,onPlaying,onError}:{originalLabel?:string;sourceFrames?:number[];current:string,candidate:string,master:RefObject<HTMLVideoElement|null>,time:number,onTime:(v:number)=>void,onPlaying:(v:boolean)=>void,onError:()=>void}){
 const [loading,setLoading]=useState(true);
 const original=useRef<HTMLVideoElement>(null);const initial=useRef(time);
 const originalTime=(t:number)=>sourceFrames?.length?sourceFrames[Math.min(sourceFrames.length-1,Math.max(0,Math.floor(t*30+1e-5)))]/30:t;
 useEffect(()=>{let raf=0;let disposed=false;
  const seekPair=()=>{const a=original.current,b=master.current;if(a&&b&&a.readyState>=1){setLoading(true);a.pause();a.currentTime=originalTime(b.currentTime);}};
 const player=master.current;player?.addEventListener('seeking',seekPair);
 const sync=()=>{const a=original.current,b=master.current;if(a&&b&&a.readyState>=2){setLoading(a.seeking||b.seeking||b.readyState<2||Math.abs(originalTime(b.currentTime)-a.currentTime)>.12);const drift=originalTime(b.currentTime)-a.currentTime;if(((sourceFrames||b.paused)&&Math.abs(drift)>.001)||Math.abs(drift)>.12)a.currentTime=originalTime(b.currentTime);if(sourceFrames||b.paused||b.ended||b.readyState<3)a.pause();else if(a.paused)void a.play().catch(()=>{});a.playbackRate=b.playbackRate*(Math.abs(drift)>.025?(drift>0?1.04:.96):1);}if(!disposed)raf=requestAnimationFrame(sync);};raf=requestAnimationFrame(sync);return()=>{disposed=true;player?.removeEventListener('seeking',seekPair);cancelAnimationFrame(raf);original.current?.pause();};
 },[current,candidate,master,sourceFrames]);
 return <div className="stacked-comparison" aria-label="Synchronized current and candidate comparison"><>{loading&&<p role="status">Synchronizing comparison frames…</p>}</><section><span>{originalLabel} · original audio muted</span><video ref={original} src={current} muted playsInline preload="auto" onLoadedMetadata={e=>{const b=master.current;if(b)e.currentTarget.currentTime=originalTime(b.currentTime)}} onError={onError}/></section><section><span>Candidate · playback audio</span><video ref={master} src={candidate} playsInline preload="auto" onLoadedMetadata={e=>{e.currentTarget.currentTime=Math.min(initial.current,Math.max(0,e.currentTarget.duration-1/30));onPlaying(false)}} onTimeUpdate={e=>onTime(e.currentTarget.currentTime)} onSeeked={e=>onTime(e.currentTarget.currentTime)} onPlay={()=>onPlaying(true)} onPause={()=>onPlaying(false)} onEnded={()=>onPlaying(false)} onError={onError}/></section></div>
}
