import {transformationRequest} from '../transformation-request.mjs';
import {useEffect,useRef,useState} from 'react';
import './TransformationReview.css';
type Point=[number,number];type Mask={time:number;points:Point[]};
type Source={id:string;label:string;url:string;origin:number};
type Project={width:number;height:number;id:string;activeRevisionId:string;revisions:{id:string;url:string}[]};
type Mode='aligned'|'foreground'|'scene';
async function call(url:string,body?:unknown){const r=await fetch(url,body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d.error||'Request failed');return d;}
export function TransformationReview({project,start,end,masks,protectedAreas=[],onRequest,onReady}:{project:Project;start:number;end:number;masks:Mask[];protectedAreas?:Point[][];onRequest:(text:string)=>void;onReady:(candidate:any)=>void}){
 const [open,setOpen]=useState(false),[sources,setSources]=useState<Source[]>([]),[sourceId,setSourceId]=useState(''),[description,setDescription]=useState('');
 const [outline,setOutline]=useState<Point[]>([]),[envelope,setEnvelope]=useState<Point[]>([]),[track,setTrack]=useState<Mask[]>([]);
 const [tool,setTool]=useState<'replacement'|'area'>('replacement'),[time,setTime]=useState(start),[policy,setPolicy]=useState('fixed'),[reviewed,setReviewed]=useState(false),[mode,setMode]=useState<Mode>('aligned');
 const [offset,setOffset]=useState(0),[placement,setPlacement]=useState({scale:1,x:0,y:0});
 const [busy,setBusy]=useState(false),[phase,setPhase]=useState(''),[error,setError]=useState(''),[length,setLength]=useState(0),[loaded,setLoaded]=useState('');
 const original=useRef<HTMLVideoElement>(null),replacement=useRef<HTMLVideoElement>(null),dialog=useRef<HTMLDialogElement>(null);
 const draftKey=`flipframe-transform-v1:${project.id}:${project.activeRevisionId}:${start}:${end}`;
 useEffect(()=>{const show=()=>setOpen(true);window.addEventListener('open-transformation-review',show);return()=>window.removeEventListener('open-transformation-review',show);},[]);
 const boundarySignature=JSON.stringify([masks,protectedAreas]);
 useEffect(()=>setReviewed(false),[boundarySignature]);
 useEffect(()=>{
  let d:any={};try{const saved=JSON.parse(localStorage.getItem(draftKey)||'null');if(saved?.version===1)d=saved;}catch{}
  setSourceId(typeof d.sourceId==='string'?d.sourceId:'');setTrack(Array.isArray(d.track)?d.track:[]);setOutline(Array.isArray(d.outline)?d.outline:[]);setEnvelope(Array.isArray(d.envelope)?d.envelope:[]);
  setMode(['aligned','foreground','scene'].includes(d.mode)?d.mode:'aligned');setOffset(Number.isFinite(d.offset)?d.offset:0);setPlacement(d.placement&&['scale','x','y'].every(k=>Number.isFinite(d.placement[k]))?d.placement:{scale:1,x:0,y:0});setPolicy(d.policy==='align'?'align':'fixed');setReviewed(false);setTime(start);setLoaded(draftKey);
 },[draftKey,start]);
 useEffect(()=>{if(loaded!==draftKey)return;try{localStorage.setItem(draftKey,JSON.stringify({version:1,sourceId,track,outline,envelope,mode,offset,placement,policy}));}catch{setError('Transformation draft could not be saved in this browser. Keep this review open.');}},[loaded,draftKey,sourceId,track,outline,envelope,mode,offset,placement,policy]);
 const source=sources.find(s=>s.id===sourceId),originalUrl=project.revisions.find(r=>r.id===project.activeRevisionId)?.url;
 useEffect(()=>{if(open){dialog.current?.showModal();call(`/api/projects/${project.id}/transformation/sources`).then(setSources).catch(e=>setError(e.message));}else dialog.current?.close();},[open,project.id]);
 useEffect(()=>{if(original.current)original.current.currentTime=time;if(replacement.current)replacement.current.currentTime=offset+time-start;},[time,offset,start,sourceId]);
 const current=track.find(m=>Math.abs(m.time-time)<1/60),frames=Array.from({length:Math.max(0,Math.ceil(end*30-1e-7)-Math.ceil(start*30-1e-7))},(_,i)=>(Math.ceil(start*30-1e-7)+i)/30);
 const sourceComplete=frames.every(t=>masks.some(m=>Math.abs(m.time-t)<1e-5)),trackComplete=frames.every(t=>track.some(m=>Math.abs(m.time-t)<1e-5));
 const complete=!!source&&end>start&&length>=offset+end-start-1e-6;
 async function wait(job:any){while(['queued','running'].includes(job.status)){setPhase(job.phase||'Working locally…');await new Promise(r=>setTimeout(r,1200));job=await call(`/api/jobs/${job.id}`);}if(job.status!=='completed')throw Error(job.error||'Local preparation failed');return job.result;}
 async function work(action:'track'|'render'){
  setBusy(true);setError('');setPhase(action==='track'?'Tracking the replacement…':'Checking and building the local preview…');
  try{const result=await wait(await call(`/api/projects/${project.id}/transformation/${action}`,{baseRevisionId:project.activeRevisionId,sourceId,start,end,candidateOffset:offset,time,points:outline,masks,protectedAreas,replacementMasks:track,envelope,cameraPolicy:policy,reviewed,mode,placement,sceneApproved:mode==='scene'&&reviewed}));
   if(action==='track'){setTrack(result.masks||[]);setReviewed(false);setOutline([]);setPhase('Replacement tracked. Scrub the range to review its borders.');}
   else{onReady(result);setOpen(false);setPhase('');}
  }catch(e){setPhase('');setError(e instanceof Error?e.message:'Local operation failed');}finally{setBusy(false);}
 }
 function draw(e:React.MouseEvent<SVGSVGElement>,which:'replacement'|'area'){
  if(busy||mode==='scene'||tool!==which)return;const r=e.currentTarget.getBoundingClientRect();const p:Point=[Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))];
  setReviewed(false);if(which==='replacement'){setTrack([]);setOutline(x=>x.length<64?[...x,p]:x);}else setEnvelope(x=>x.length<64?[...x,p]:x);
 }
 const vertices=(p:Point[])=>p.map(([x,y])=>`${x*1000},${y*1000}`).join(' ');
 return <><button className="transformation-entry" onClick={()=>setOpen(true)}>Transform object or scene</button><dialog className="transformation-review" ref={dialog} onCancel={e=>{if(busy)e.preventDefault();else setOpen(false);}}>
 <header><div><h2>Review a transformation</h2><p>Reuse saved footage. Your original stays intact until you apply a preview.</p></div><button disabled={busy} onClick={()=>setOpen(false)}>Return to conversation</button></header>
 <label>Edit scope<select disabled={busy} value={mode} onChange={e=>{setMode(e.target.value as Mode);setReviewed(false);setError('');}}><option value="aligned">Preserve scene · align cameras</option><option value="foreground">Transfer foreground · retain generated viewpoint</option><option value="scene">Replace whole scene · allow camera and environment changes</option></select></label>
 {mode==='scene'?<p role="alert">The entire picture inside {start.toFixed(2)}–{end.toFixed(2)}s will change, including the camera and background. Review the cuts at both ends. Object masks do not limit this mode.</p>:mode==='foreground'?<p>Use observed original background and only the replacement foreground. Requires a stable source camera and sufficient exposed background. Placement cannot correct the robot’s 3D viewpoint.</p>:<p>Keep the original scene. Alignment stops if the generated background cannot be matched reliably.</p>}
 <label>Existing generated or imported footage<select disabled={busy} value={sourceId} onChange={e=>{const next=sources.find(s=>s.id===e.target.value);setSourceId(e.target.value);setOffset(Math.max(0,start-(next?.origin||0)));setTrack([]);setOutline([]);setReviewed(false);setLength(0);setError('');}}><option value="">Choose footage—no new generation</option>{sources.map(s=><option key={s.id} value={s.id}>{s.label}</option>)}</select></label>
 <label>Start replacement footage at (seconds)<input type="number" min={0} max={Math.max(0,length)} step={1/30} value={offset} disabled={busy} onChange={e=>{setOffset(Math.max(0,Number(e.target.value)));setTrack([]);setReviewed(false);}}/></label><p>Selected duration: {(end-start).toFixed(2)}s. No looping, freezing or stretching is applied.</p>
 <div className="transformation-panes"><section><h3>Original{mode!=='scene'?' · permitted repair area':''}</h3><div className="transformation-canvas" style={{aspectRatio:`${project.width}/${project.height}`}}><video ref={original} src={originalUrl} muted preload="auto" onLoadedMetadata={()=>{if(original.current)original.current.currentTime=time;}}/>{mode!=='scene'&&<svg viewBox="0 0 1000 1000" preserveAspectRatio="none" onClick={e=>draw(e,'area')} aria-label="Draw permitted repair area"><polygon points={vertices(envelope)}/>{masks.filter(m=>Math.abs(m.time-time)<1/60).map(m=><polygon className="source-outline" key={m.time} points={vertices(m.points)}/>)}</svg>}</div></section>
 <section><h3>Replacement{mode!=='scene'?' · independent outline':''}</h3><div className="transformation-canvas" style={{aspectRatio:`${project.width}/${project.height}`}}>{source&&<video key={source.id} ref={replacement} src={source.url} muted preload="auto" onLoadedMetadata={e=>{setLength(e.currentTarget.duration);e.currentTarget.currentTime=offset+time-start;}}/>}{mode!=='scene'&&<svg viewBox="0 0 1000 1000" preserveAspectRatio="none" onClick={e=>draw(e,'replacement')} aria-label="Draw replacement outline"><polygon points={vertices(outline.length?outline:current?.points||[])}/></svg>}</div></section></div>
 <label>Review frame · {time.toFixed(2)}s<input aria-label="Transformation review frame" type="range" min={start} max={Math.max(start,end-1/30)} step={1/30} value={time} disabled={busy} onChange={e=>{setTime(Number(e.target.value));setOutline([]);}}/></label>
 {source&&!complete&&length>0&&<p role="alert">Replacement footage is too short at this offset. Choose an earlier offset or adjust the selection explicitly.</p>}
 {mode!=='scene'&&<>{!sourceComplete&&<p role="alert">Some original frames need object borders. Correct them in the editor.</p>}<div className="transformation-tools"><button aria-pressed={tool==='replacement'} disabled={busy} onClick={()=>setTool('replacement')}>1 · Outline replacement</button><button disabled={busy||outline.length<3||!complete} onClick={()=>void work('track')}>Track replacement with SAM</button><button aria-pressed={tool==='area'} disabled={busy} onClick={()=>setTool('area')}>2 · Draw permitted repair area</button><button disabled={busy} onClick={()=>{setReviewed(false);if(tool==='replacement'){setOutline([]);setTrack([]);}else setEnvelope([]);}}>Clear active drawing</button></div>{track.length>0&&!trackComplete&&<p role="alert">Replacement tracking has gaps. Correct the outline and track again or choose a shorter range.</p>}
 {mode==='aligned'?<label>Camera handling<select disabled={busy} value={policy} onChange={e=>{setPolicy(e.target.value);setReviewed(false);}}><option value="fixed">Keep original camera · stop if it differs</option><option value="align">Try aligning generated camera to original</option></select></label>:<fieldset disabled={busy}><legend>Foreground placement · fixed across this range</legend>{(['scale','x','y'] as const).map(k=><label key={k}>{k==='scale'?'Uniform scale':k==='x'?'Horizontal shift (frame widths)':'Vertical shift (frame heights)'}<input type="number" min={k==='scale'?.25:-1} max={k==='scale'?3:1} step={.05} value={placement[k]} onChange={e=>{setPlacement(p=>({...p,[k]:Number(e.target.value)}));setReviewed(false);}}/></label>)}</fieldset>}</>}
 <label><input type="checkbox" checked={reviewed} disabled={busy||!complete||(mode!=='scene'&&(!trackComplete||!sourceComplete||envelope.length<3))} onChange={e=>setReviewed(e.target.checked)}/>{mode==='scene'?' I approve replacing the whole picture in this range, including camera and environment.':' I reviewed both object tracks and permit reconstruction inside the drawn area.'}</label>
 <details><summary>Need different replacement footage?</summary><p>This prepares a request only. Review the price in conversation before generating.</p><label>Describe the replacement<textarea value={description} maxLength={1800} disabled={busy} onChange={e=>setDescription(e.target.value)}/></label><button disabled={busy||!description.trim()} onClick={()=>{onRequest(transformationRequest(description,mode));setOpen(false);}}>Prepare replacement request in conversation</button></details>
 <p role="status" aria-live="polite">{phase}{busy?' Please wait; no generation is being submitted.':''}</p>{error&&<p role="alert">{error}</p>}<button className="primary" disabled={busy||!reviewed||!complete||(mode!=='scene'&&(!sourceComplete||!trackComplete))} onClick={()=>void work('render')}>Build local preview · no API cost</button>
 </dialog></>;
}
